"""Gameplay Tag files under Config/Tags (TAG-3, GEN-1).

`Gridlands.ini` is hand-written system vocabulary. `GeneratedFromData.ini` is
written by `Tools/data.sh generate` from era, band and yield definitions, and
the validator fails when it is stale.
"""

from __future__ import annotations

import re
from pathlib import Path

TAGS_DIR = "Config/Tags"
GENERATED_FILE = "Config/Tags/GeneratedFromData.ini"
GENERATING_KINDS = ("era", "band", "yield")
SECTION = "[/Script/GameplayTags.GameplayTagsList]"
LINE = re.compile(r'^\+?GameplayTagList=\(Tag="([^"]+)"')


def declared_tags(repo_root: Path) -> set[str]:
    tags: set[str] = set()
    for path in sorted((repo_root / TAGS_DIR).glob("*.ini")):
        for line in path.read_text(encoding="utf-8").splitlines():
            match = LINE.match(line.strip())
            if match:
                tags.add(match.group(1))
    return tags


SCHEMA_EXPORT = "Data/_registry/schema.generated.json"


def render_schema_export() -> str:
    """Per-kind key paths the Python schemas allow; the C++ loader is tested against this (ADR-0021)."""
    import json

    from . import schema

    kinds = {kind: sorted(schema.key_paths(spec)) for kind, spec in sorted(schema.SCHEMAS.items())}
    body = {"schemaVersion": 1, "comment": "GENERATED by Tools/data.sh generate. Do not edit.", "kinds": kinds}
    return json.dumps(body, indent=1, sort_keys=True) + "\n"


def render_generated(ds) -> str:
    rows = []
    for entity in sorted(ds.entities.values(), key=lambda e: e.data.get("tag", "")):
        if entity.kind in GENERATING_KINDS and isinstance(entity.data.get("tag"), str):
            comment = f"{entity.id}: {entity.data.get('displayName', '')}".replace('"', "'")
            rows.append(f'GameplayTagList=(Tag="{entity.data["tag"]}",DevComment="{comment}")')
    header = [
        "; GENERATED by Tools/data.sh generate from Data/{era,band,yield}. Do not edit by hand.",
        SECTION,
    ]
    return "\n".join(header + rows) + "\n"
