#include "Anchors/GLAnchorExport.h"

#include "Content/GLContentId.h"
#include "Components/PrimitiveComponent.h"
#include "Engine/Level.h"
#include "Engine/World.h"
#include "GameFramework/Actor.h"
#include "UObject/Package.h"
#include "World/GLAnchorComponent.h"

namespace GLAnchorExport
{
	FString ShortName(const FString& CellId)
	{
		FString Left, Right;
		return CellId.Split(TEXT("."), &Left, &Right, ESearchCase::CaseSensitive, ESearchDir::FromEnd) ? Right : CellId;
	}

	/**
	 * A component's world transform from its serialized relative transforms. It does not depend on
	 * registration, so an uninitialized loaded map (commandlet) and the editor's live copy (tests)
	 * export identical bytes.
	 */
	FTransform SerializedWorldTransform(const USceneComponent* Component)
	{
		FTransform Result = Component->GetRelativeTransform();
		for (const USceneComponent* Parent = Component->GetAttachParent(); Parent; Parent = Parent->GetAttachParent())
		{
			Result = Result * Parent->GetRelativeTransform();
		}
		return Result;
	}

	UWorld* LoadMap(const FString& LongPackageName)
	{
		UPackage* Package = LoadPackage(nullptr, *LongPackageName, LOAD_None);
		return Package ? UWorld::FindWorldInPackage(Package) : nullptr;
	}

	FString FilePathForCell(const FString& CellId)
	{
		return FString::Printf(TEXT("Data/anchor/%s.generated.json"), *ShortName(CellId));
	}

	FString Render(UWorld* World, const FString& CellId, TArray<FString>& OutProblems)
	{
		struct FAnchorRow
		{
			FString Id;
			FVector Location;
			double Yaw;
			FVector Extent;
		};
		TArray<FAnchorRow> Rows;
		const FString Prefix = FString::Printf(TEXT("anchor.%s."), *ShortName(CellId));
		// A loaded map's world is not initialized, so walk its persistent level directly.
		for (AActor* It : World->PersistentLevel->Actors)
		{
			if (!It)
			{
				continue;
			}
			TArray<UGLAnchorComponent*> Anchors;
			It->GetComponents(Anchors);
			for (const UGLAnchorComponent* Anchor : Anchors)
			{
				const FString Id = Anchor->AnchorId.ToString();
				FString Problem;
				if (!GLContentId::IsValid(Id, &Problem))
				{
					OutProblems.Add(FString::Printf(TEXT("%s: anchor id '%s': %s"), *It->GetName(), *Id, *Problem));
					continue;
				}
				if (!Id.StartsWith(Prefix, ESearchCase::CaseSensitive))
				{
					OutProblems.Add(FString::Printf(TEXT("%s: anchor '%s' must start with '%s'"), *It->GetName(), *Id, *Prefix));
					continue;
				}
				const USceneComponent* Root = It->GetRootComponent();
				if (!Root)
				{
					OutProblems.Add(FString::Printf(TEXT("%s: anchored actor has no root component"), *It->GetName()));
					continue;
				}
				const FTransform RootTransform = SerializedWorldTransform(Root);
				FBox Bounds(ForceInit);
				TArray<UPrimitiveComponent*> Primitives;
				It->GetComponents(Primitives);
				for (const UPrimitiveComponent* Primitive : Primitives)
				{
					Bounds += Primitive->CalcBounds(SerializedWorldTransform(Primitive)).GetBox();
				}
				Rows.Add({ Id, RootTransform.GetLocation(), RootTransform.Rotator().Yaw, Bounds.IsValid ? Bounds.GetExtent() : FVector::ZeroVector });
			}
		}
		Rows.Sort([](const FAnchorRow& A, const FAnchorRow& B) { return A.Id < B.Id; });
		for (int32 Index = 1; Index < Rows.Num(); ++Index)
		{
			if (Rows[Index].Id == Rows[Index - 1].Id)
			{
				OutProblems.Add(FString::Printf(TEXT("duplicate anchor id '%s'"), *Rows[Index].Id));
			}
		}

		// "+ 0.0" turns -0.0 into 0.0 so output never flips sign spuriously.
		auto Vec = [](const FVector& V) { return FString::Printf(TEXT("[%.1f, %.1f, %.1f]"), V.X + 0.0, V.Y + 0.0, V.Z + 0.0); };
		FString Out = FString::Printf(TEXT("{\n \"schemaVersion\": 1,\n \"comment\": \"GENERATED by Tools/export-anchors.sh from the cell's map. Do not edit.\",\n \"cell\": \"%s\",\n \"anchors\": ["), *CellId);
		for (int32 Index = 0; Index < Rows.Num(); ++Index)
		{
			const FAnchorRow& Row = Rows[Index];
			Out += FString::Printf(TEXT("%s\n  {\"id\": \"%s\", \"transform\": {\"location\": %s, \"yaw\": %.1f}, \"boundsExtent\": %s}"),
				Index == 0 ? TEXT("") : TEXT(","), *Row.Id, *Vec(Row.Location), Row.Yaw + 0.0, *Vec(Row.Extent));
		}
		Out += Rows.Num() > 0 ? TEXT("\n ]\n}\n") : TEXT("]\n}\n");
		return Out;
	}
}
